# syntax=docker/dockerfile:1
FROM ubuntu:24.04

ARG RELEASE
ARG LAUNCHPAD_BUILD_ARCH
ARG DEBIAN_FRONTEND=noninteractive
CMD ["/bin/bash"]

# Compatibility for 32 bit OpenGL / X11 applications and 64 bit
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    libxau6 \
    libxau6:i386 \
    libxdmcp6 \
    libxdmcp6:i386 \
    libxcb1 \
    libxcb1:i386 \
    libxext6 \
    libxext6:i386 \
    libx11-6 \
    libx11-6:i386 \
    pkg-config \
    libglvnd-dev \
    libglvnd-dev:i386 \
    libgl1-mesa-dev \
    libgl1-mesa-dev:i386 \
    libegl1-mesa-dev \
    libegl1-mesa-dev:i386 \
    libgles2-mesa-dev \
    libgles2-mesa-dev:i386 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Nvidia Graphics compatibility: makes Nvidia libs available and visible (for both 32 and 64 bit apps)
ENV NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,compat32,utility
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf &&\
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

RUN apt update && apt install software-properties-common -y && \
    add-apt-repository universe
# Essentials pkgs setup
RUN apt-get update  && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        cppcheck \
        curl \
        doxygen \
        gdb \
        git \
        gnupg2\
        libbluetooth-dev \
        libcwiid-dev \
        libgoogle-glog-dev \
        libspnav-dev \
        libusb-dev \
        locales \
        lsb-release \
        mercurial \
        python3-dbg \
        python3-empy \
        python3-psutil \
        python3-venv \
        software-properties-common \
        sudo \
        tzdata \
        vim \
        wget \
        tmux \
        psmisc \
        build-essential git cmake cmake-curses-gui \
        ycm-cmake-modules \
        libeigen3-dev \
        libace-dev \
        libedit-dev \
        libsqlite3-dev \
        libtinyxml-dev \
        qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev \
        qml-module-qtquick2 qml-module-qtquick-window2 \
        qml-module-qtmultimedia qml-module-qtquick-dialogs \
        qml-module-qtquick-controls qml-module-qt-labs-folderlistmodel \
        qml-module-qt-labs-settings \
        libqcustomplot-dev \
        libgraphviz-dev \
        libjpeg-dev \
        gedit \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-libav \
        glpk-doc \
        glpk-utils \
        libglpk-dev \
        libglpk40 \
        terminator \
        plocate \
        x11vnc && \
        apt clean && \
        rm -rf /var/lib/apt/lists/*

# Xorg setup
RUN apt update && \
    apt install -y xfce4 xfce4-goodies xserver-xorg-video-dummy xserver-xorg-legacy && \
    sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# ROS2 preparation
RUN locale-gen en_US en_US.UTF-8 &&   update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 &&   export LANG=en_US.UTF-8 && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb


# ROS2 install
ENV ROS_DISTRO=jazzy
RUN apt update && apt install -y python3-rosdep python3-vcstool python3-colcon-common-extensions  python3-colcon-mixin \
    ros-jazzy-control-msgs     ros-jazzy-controller-manager     ros-jazzy-desktop     ros-jazzy-generate-parameter-library \
    ros-jazzy-geometric-shapes     ros-jazzy-gripper-controllers     ros-jazzy-joint-state-broadcaster     ros-jazzy-joint-state-publisher \
    ros-jazzy-joint-trajectory-controller     ros-jazzy-moveit-common     ros-jazzy-moveit-configs-utils     ros-jazzy-moveit-core  \
    ros-jazzy-moveit-hybrid-planning     ros-jazzy-moveit-msgs     ros-jazzy-moveit-resources-panda-moveit-config    \
    ros-jazzy-moveit-ros-move-group     ros-jazzy-moveit-ros-perception     ros-jazzy-moveit-ros-planning   \
    ros-jazzy-moveit-ros-planning-interface     ros-jazzy-moveit-ros-visualization     ros-jazzy-moveit-servo     ros-jazzy-moveit-visual-tools   \
    ros-jazzy-moveit     ros-jazzy-rmw-cyclonedds-cpp     ros-jazzy-ros2-control     ros-jazzy-rviz-visual-tools     ros-jazzy-xacro \
    ros-jazzy-test-msgs   ros-jazzy-rqt*  ros-jazzy-ros-gz && apt clean && rm -rf /var/lib/apt/lists/*

RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list' &&\
    wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add - &&\
    apt update && \
    apt install -y \
        libgz-sim8-dev \
        libgz-tools2-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# USER definition
RUN useradd -l -u 33334 -G sudo -md /home/ecub_docker -s /bin/bash -p ecub_docker ecub_docker &&     sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
ENV USERNAME=ecub_docker
USER $USERNAME
WORKDIR /home/$USERNAME

# Git Setup
ARG GIT_USERNAME
ARG GIT_USER_EMAIL
RUN git config --global user.name "${GIT_USERNAME}" && git config --global user.email ${GIT_USER_EMAIL}

### Robotology Superbuild Install Section
ARG BUILD_TYPE=Release

# Superbuild cloning
RUN sudo apt update && git clone https://github.com/robotology/robotology-superbuild && \
    cd robotology-superbuild && git checkout v2025.11.0  && \
    sudo chmod +x scripts/install_apt_dependencies.sh && \
    sudo chmod +x scripts/install_apt_python_dependencies.sh && \
    sudo bash ./scripts/install_apt_dependencies.sh &&\
    sudo apt clean && \
    sudo rm -rf /var/lib/apt/lists/*

# Gz-sim
RUN git clone https://github.com/CLIUtils/CLI11 && \
    cd CLI11/ && \
    mkdir build && \
    cd build && \
    git submodule update --init && \
    cmake .. && \
    cmake --build . && \
    sudo cmake --install .

RUN cd robotology-superbuild && git checkout v2025.11.0 && mkdir build && cd build && \
    export OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4 && cmake -DROBOTOLOGY_ENABLE_CORE=ON \
    -DROBOTOLOGY_ENABLE_DYNAMICS=ON \
    -DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS=ON \
    -DROBOTOLOGY_USES_GZ=ON .. && \
    make -j8 && make install -j8

RUN sudo ln -s /usr/local/share/bash-completion/completions/yarp /usr/share/bash-completion/completions
# Environment setup for simulation
ENV YARP_COLORED_OUTPUT=1
ENV WalkingControllers_INSTALL_DIR=/home/$USERNAME/robotology-superbuild/build/install
ENV YARP_DATA_DIRS=$YARP_DATA_DIRS:$WalkingControllers_INSTALL_DIR/share/yarp
ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:/home/$USERNAME/robotology-superbuild/build/install/share/iCub
ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:/home/$USERNAME/robotology-superbuild/build/install/share/ergoCub
ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:/home/$USERNAME/robotology-superbuild/build/install/share/ICUBcontrib
ENV PATH=${PATH}:/home/$USERNAME/robotology-superbuild/build/install/bin
ENV YARP_ROBOT_NAME=ergoCubGazeboSN001_minContacts
ENV PYTHONPATH=${PYTHONPATH}:/home/$USERNAME/robotology-superbuild/build/install/lib/python3
ENV GZ_SIM_YARP_PLUGINS_SOURCE_DIR=/home/$USERNAME/gz-sim-yarp-plugins
ENV GZ_SIM_YARP_PLUGINS_DIR=${GZ_SIM_YARP_PLUGINS_SOURCE_DIR}/build
ENV GZ_SIM_SYSTEM_PLUGIN_PATH=${GZ_SIM_SYSTEM_PLUGIN_PATH}:${GZ_SIM_YARP_PLUGINS_DIR}/lib
ENV GZ_SIM_RESOURCE_PATH=${GZ_SIM_RESOURCE_PATH}:/home/ecub_docker/robotology-superbuild/src/ergocub-software/urdf

RUN git clone https://github.com/robotology/gz-sim-yarp-plugins &&\
    cd gz-sim-yarp-plugins && git checkout v0.5.3 && mkdir build && cd build && \
    /bin/bash -c "source /opt/ros/jazzy/setup.bash; cmake .. -DBUILD_gz-sim-yarp-worldinterface-system=ON && make -j8"

# Bashrc setup
RUN echo "export PATH=\$PATH:/home/$USERNAME/robotology-superbuild/build/install/bin" >> ~/.bashrc && \
    echo "alias goToBuildSuperbuild='cd ../../build/src/\${PWD##*/}'" >> ~/.bashrc && \
    echo "alias 0_yarpserver='yarpserver --write'" >> ~/.bashrc && \
    echo "alias 1_gazebo_warehouse='export YARP_CLOCK=/clock && gz sim /home/ecub_docker/ros2_workspace/src/ergocub_navigation/sim/warehouse.sdf --verbose'" >> ~/.bashrc && \
    echo "alias 2_spawn_robot='ros2 run ros_gz_sim create -file /home/ecub_docker/robotology-superbuild/src/ergocub-software/urdf/ergoCub/robots/ergoCubGazeboSN001_minContacts/model.urdf -name ergocub -z 0.8'" >> ~/.bashrc && \
    echo "alias walking_retargeting='export YARP_CLOCK=/clock WalkingModule --from /home/$USERNAME/robotology-superbuild/src/walking-controllers/src/WalkingModule/app/robots/ergoCubGazeboV1/dcm_walking_iFeel_joint_retargeting.ini'" >> ~/.bashrc && \
    echo "alias launch_wbd_interface='yarprobotinterface --config /home/$USERNAME/robotology-superbuild/src/ergocub-software/urdf/ergoCub/conf/launch_wholebodydynamics_ecub.xml'" >> ~/.bashrc && \
    echo "alias merge_ports='yarp merge --input /wholeBodyDynamics/right_foot_front/cartesianEndEffectorWrench:o /wholeBodyDynamics/left_foot_front/cartesianEndEffectorWrench:o --output /feetWrenches'" >> ~/.bashrc && \
    echo "alias col_build='colcon build --symlink-install'" >> ~/.bashrc && \
    echo "source /opt/ros/jazzy/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "source /home/$USERNAME/ros2_workspace/install/setup.bash" >> /home/$USERNAME/.bashrc && \
    echo "export LD_LIBRARY_PATH=/home/ecub_docker/robotology-superbuild/build/install/lib:\$LD_LIBRARY_PATH" >> /home/$USERNAME/.bashrc


EXPOSE 8080
EXPOSE 8888
EXPOSE 6080
EXPOSE 10000/tcp 10000/udp

# Nav2
RUN sudo apt update && sudo apt install -y ros-jazzy-navigation2 ros-jazzy-nav2-bringup ros-jazzy-perception ros-jazzy-slam-toolbox \
    && sudo apt clean && \
    sudo rm -rf /var/lib/apt/lists/*
# Adding pointcloud to laserscan and ergocub_navigation on ROS2 WS
SHELL ["/bin/bash", "-c"]
RUN mkdir -p /home/$USERNAME/ros2_workspace/src && cd /home/$USERNAME/ros2_workspace && \
    /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.sh && colcon build"  && \
    cd src && \
    git clone -b gz-sim https://github.com/hsp-iit/ergocub_navigation.git && \
    git clone -b jazzy https://github.com/hsp-iit/bt_nav2_ergocub.git && \
    git clone -b jazzy https://github.com/ros-perception/pointcloud_to_laserscan && \
    git clone -b jazzy https://github.com/SimoneMic/theta_star_oriented && \
    cd .. && source /opt/ros/$ROS_DISTRO/setup.bash && colcon build --symlink-install --cmake-args -DCMAKE_CXX_FLAGS=-w
ENV AMENT_PREFIX_PATH=$AMENT_PREFIX_PATH:/opt/ros/jazzy

# Adding custom worlds to gazebo
RUN sudo cp -r /home/$USERNAME/ros2_workspace/src/ergocub_navigation/docker/worlds /usr/share/gazebo-11
# XORG setup
RUN sudo cp /home/$USERNAME/ros2_workspace/src/ergocub_navigation/docker/xorg.conf /etc/X11/xorg.conf

# Update walking-comtrollers in robotology superbuild to work in navigation
RUN cd robotology-superbuild/src/walking-controllers && git remote add SimoneMic https://github.com/SimoneMic/walking-controllers && \
    git fetch SimoneMic && \
    git switch nav_integration && \
    cd ../../build/src/walking-controllers && make install -j8 && cd .

# yarp-devices-ros2
ENV AMENT_PREFIX_PATH=$AMENT_PREFIX_PATH:/home/$USERNAME/robotology-superbuild/build/install
RUN git clone https://github.com/robotology/yarp-devices-ros2 && \
    cd yarp-devices-ros2/ros2_interfaces_ws && \
    git checkout v2.0.0 && \
    source /opt/ros/jazzy/setup.sh && colcon build && \
    cd .. && mkdir build && cd build && \
    source /opt/ros/$ROS_DISTRO/setup.bash && source /home/$USERNAME/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && cmake .. -DYARP_ROS2_USE_SYSTEM_map2d_nws_ros2_msgs=ON -DYARP_ROS2_USE_SYSTEM_yarp_control_msgs=ON && make -j11 && \
    echo "source /home/$USERNAME/yarp-devices-ros2/ros2_interfaces_ws/install/local_setup.bash" >> ~/.bashrc
ENV YARP_DATA_DIRS=${YARP_DATA_DIRS}:/home/$USERNAME/yarp-devices-ros2/build/share/yarp:/home/$USERNAME/yarp-devices-ros2/build/share/yarp-devices-ros2

# ergocub-software for ros2
RUN cd robotology-superbuild/src/ergocub-software &&\
    git remote add simomic https://github.com/SimoneMic/ergocub-software && \
    git fetch simomic && \
    git stash && git switch gz_sim && \
    cd ../../build/src/ergocub-software && \
    cmake . && make install

RUN echo "source /home/$USERNAME/robotology-superbuild/build/install/share/robotology-superbuild/setup.sh" >> ~/.bashrc &&\
    sudo updatedb
